development:
  adapter: postgresql
  encoding: utf8
  database: enrolment_control_development
  pool: 5
  username: postgres
  password: '837900'
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: enrolment_control_test
  pool: 5
  username: postgres
  password: '837900'
  min_messages: WARNING
  host: localhost
  template: template0
